services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=userdb

volumes:
  mysql: {}