spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/userdb?autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update


flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}
  baselineOnMigrate: true   # flyway will automatically create baseline for database when you run migration
  #location: classpath:db/migration

